helloworld/config/routes.rb
Rails.application.routes.draw do
  get 'users/signin'
  get 'users/profile'
  get 'user/signin'
  get 've_tam_giac/index'
  get 've_table/index'
  get 'hello/index'
  root to: 'hello#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

helloworld/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
    @title_of_page = 'Trang chu'
  end
end

helloworld/app/controllers/user_controller.rb
class UserController < ApplicationController
  def signin
    @title_of_page = 'Dang nhap'
  end
end

helloworld/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signin; end

  def profile; end
end

helloworld/app/controllers/ve_table_controller.rb
class VeTableController < ApplicationController
  def index; end
end

helloworld/app/controllers/ve_tam_giac_controller.rb
class VeTamGiacController < ApplicationController
  def index
    @index_output = ''
    (0..4).each do |i|
      puts 'Hien trong terminal'
      @index_output = @index_output + '*' * i + '<br>'
      @index_output.html_safe
    end
  end
end

helloworld/app/helpers/application_helper.rb
module ApplicationHelper
  def hello
    '<i>Hello</i>'.html_safe
  end
end

helloworld/app/helpers/hello_helper.rb
module HelloHelper
end

helloworld/app/helpers/user_helper.rb
module UserHelper
end

helloworld/app/helpers/ve_table_helper.rb
module VeTableHelper
   
    def table
        a = ''
        (0..15).each do |i|
            a = a + i.to_s + ' ' + (i % 4 == 0 ? '<br>' : '')
        end
        a.html_safe
    end    
end

helloworld/app/helpers/ve_tam_giac_helper.rb
module VeTamGiacHelper
end

helloworld/app/views/hello/index.html.erb
<div id="header">
<%=link_to 'Sign In', users_signin_path, class: 'btnSignIn'%>
<%=link_to 'Profile', users_profile_path, class: 'btnProfile'%>


</div>
<div class="clearfix">
<div>
<h1>Hello#index</h1>
<h1><%=hello%>
<p>Find me in app/views/hello/index.html.erb</p>
</div>

helloworld/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=@title_of_page%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

helloworld/app/views/user/signin.html.erb
<h1 class="title">Sign-in</h1>
<form method="post">
<table>
<tr>
<td>Username</td><td><input type="text"></td>
</tr>
<tr>
<td>Password</td><td><input type="password"></td>
</tr>
<tr><td colspan="2" class="btnSignIn"><button>Sign In</button></td></tr>
</table>

</form>

helloworld/app/views/users/profile.html.erb
<h1>Users#signout</h1>
<p>Find me in app/views/users/signout.html.erb</p>
<!--<a href="<%=root_path%>">Quay lai trang chu</a>-->
<%=link_to 'Trang chu', root_path%>

helloworld/app/views/users/signin.html.erb
<form method="post">
<h1 class="title">Sign-in</h1>
<div class="username">
    <p>Username</p>
    <input type="text">
</div>
<div class="password">
    <p>Password</p>
    <input type="password">
</div>
<div><button>Sign In</button></div>
<div><a href="/user/forgot-password">Forgot password?</a></div>
</form>
<!--<a href="/">Quay lai trang chu</a>-->
<%=link_to 'Trang chu', root_path%>

helloworld/app/views/ve_table/index.html.erb
<table>
<% for i in (0..15) do %>
<%  if i % 4 == 0 %>
    <tr>
<% end %>
    <td><%=i%></td>
<% end %>
</table>

<table>
<%=table%>

</table>

helloworld/app/views/ve_tam_giac/index.html.erb
<p>Day la 1 tam giac</p>
<%= @index_output %>