QLHV/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

QLHV/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

QLHV/app/models/class_info.rb
# == Schema Information
#
# Table name: class_infos
#
#  id         :integer          not null, primary key
#  code       :string
#  counter    :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ClassInfo < ApplicationRecord
    has_many :users
end

QLHV/app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  phone      :string
#  schedule   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Profile < ApplicationRecord
    has_one :user
end

QLHV/app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  bod           :datetime
#  cmnd          :string
#  contact       :string
#  email         :string
#  first_n       :string
#  last_n        :string
#  short_n       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  class_info_id :integer
#  profile_id    :integer
#
# model User.
class User < ApplicationRecord
  belongs_to :class_info, optional: true
  belongs_to :profile, optional: true

  validates_presence_of :first_n, on: :create, message: "can't be blank"
  validates :last_n, :contact, presence: true
  validates :first_n, length: {minimum:3, maximum:20}
  validates :email, format: { with: /\A[a-zA-Z0-9\.]+@[a-zA-Z\.]+\.[a-zA-Z]+\z/ }
  def full_name
    "#{first_n} #{self.last_n}"
  end
end

QLHV/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_n, :last_n, :short_n, :class_n, :bod, :email, :contact, :cmnd)
    end
end

QLHV/app/helpers/users_helper.rb
module UsersHelper
end

QLHV/app/views/home/_mast-head.html.erb
 <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="assets/img/avataaars.svg" alt="" />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0"><%= title%></h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p>
            </div>
        </header>

QLHV/app/views/home/_nav.html.erb
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"><%= brand%></a>
                <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">About</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contact</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%= users_path %>">Hoc Vien</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<%= users_url %>">Hoc Vien URL</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><%= link_to 'Them hoc vien moi', new_user_path, class: 'nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger'%></li>
                    </ul>
                </div>
            </div>
        </nav>

QLHV/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QLHV</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" /> %>
  </head>

  <body>
  <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>